# Generated by Django 5.0.6 on 2026-02-17 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment_riskassessment_clinicalalert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('mental_health', 'Mental Health'), ('food_support', 'Food Support'), ('transport', 'Transport'), ('financial', 'Financial Aid'), ('housing', 'Housing'), ('chronic_care', 'Chronic Care'), ('wellness', 'Wellness')], max_length=30)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('eligibility', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'active'], name='api_communi_categor_a083b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_severity', models.PositiveSmallIntegerField(default=0)),
                ('mood_score', models.PositiveSmallIntegerField(default=5)),
                ('medication_taken', models.BooleanField(default=True)),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='api.patient')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='api_patient_created_5db0b2_idx'), models.Index(fields=['symptom_severity'], name='api_patient_symptom_8f882d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResourceReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('contacted', 'Contacted'), ('enrolled', 'Enrolled'), ('completed', 'Completed'), ('declined', 'Declined')], default='recommended', max_length=20)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('impact_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='api.patient')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='api.communityresource')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='api_resourc_status_499b1f_idx')],
            },
        ),
    ]
