# Generated by Django 5.0.6 on 2026-07-01 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_domainevent_workflowrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export')], max_length=20)),
                ('resource_type', models.CharField(help_text='Model/resource name, e.g. "Patient".', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='Primary key of the affected record, if any.', max_length=64)),
                ('detail', models.CharField(blank=True, help_text='Short human-readable context, e.g. filter params.', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='api_auditlo_resourc_c074b3_idx'), models.Index(fields=['actor', 'created_at'], name='api_auditlo_actor_i_f8e456_idx'), models.Index(fields=['action', 'created_at'], name='api_auditlo_action_e69819_idx')],
            },
        ),
    ]
